### ISSUE TITLE
해당 위치 지역 json을 가져오지 못함 ( ex. 성남지역)- %20 공백들어가서 그런듯

### ISSUE THREAD

**Issue by kjs850** [kjs850/gpay#3]
![image](https://user-images.githubusercontent.com/4270992/79923012-b324ef80-846f-11ea-91ec-6fd59dca0000.png)

https://g-pay.info/json/%EA%B2%BD%EA%B8%B0%EB%8F%84%ED%99%94%EC%84%B1%EC%8B%9C%EC%A0%95%EB%82%A8%EB%A9%B4%20%EA%B3%A0%EC%A7%80%EB%A6%AC_restaurant.json

![image](https://user-images.githubusercontent.com/4270992/79922932-82dd5100-846f-11ea-84e3-263c7ee60e4f.png)

원래 호출되야 하는데 url
![image](https://user-images.githubusercontent.com/4270992/79922973-9a1c3e80-846f-11ea-8dd8-857888b3ac20.png)

**Comment by kjs850** [comment]
![image](https://user-images.githubusercontent.com/4270992/79923501-989f4600-8470-11ea-9bf2-b342f5dc643f.png)
비교 : https://data.gg.go.kr/portal/data/service/selectServicePage.do?page=1&rows=10&sortColumn=&sortDirection=&infId=3NPA52LBMO36CQEQ1GMY28894927&infSeq=2&order=&loc=#none

**Comment by boojongmin** [comment]
0cb80b7e876791309f0ddbb98cac4db34f1e1462

**Comment by boojongmin** [comment]
성남지역은 json에 카테고리 정보가 없음
